### ISSUE TITLE
coordinate system

### ISSUE THREAD

**Issue by tyegagne** [anstoc/ImpactMapper#1]
Hi,

When loading raster input, (i.e. X-Y and value data) do the XY coordinates have to be in a particular reference system? I'm trying to load the attached file and it will not appear in the viewer?

[reproex.txt](https://github.com/anstoc/EcoImpactMapper/files/1189014/reproex.txt)

**Comment by tyegagne** [comment]
The read-in is sensitive to the " " of chr string headers.

**Comment by anstoc** [comment]
Hi,

you probably figured it out but I can read the file without problems 
using the settings in the screenshot below. Generally, any projected 
coordinate system should work. As you're writing via github, note that 
there's also a Figshare site with a tutorial and example data 
(https://figshare.com/articles/ImpactMapper/1519342) and that the most 
recent (including some experimental) code is on 
https://github.com/anstoc/EcoImpactMapper_Dev.

Best,
Andy

**Comment by tyegagne** [comment]
Hi Andy,


Thanks for the reply, I believe I resolved my issue.


Also, have you thought about building an R wrapper to load and implement EcoImpactMapper? It would be nice for reproducible work, outside of the conventional GUI click and point.


Thanks!

T



Tyler Gagne
Assistant Research Scientist
P 831-648-4967


[http://www.montereybayaquarium.org/storage/email/logo_signature.gif]   Monterey Bay Aquarium
886 Cannery Row, Monterey, CA 93940
www.montereybayaquarium.org<http://www.montereybayaquarium.org>
Our mission is to inspire conservation of the ocean.



________________________________

**Comment by anstoc** [comment]
Hi again,

thanks for the suggestion. I've started to write an R wrapper but it's a
side project, I'm for now the only one working on it, and I'd like to
replace some ad-hoc aspects of the sensitivity analysis methods with
something more theoretically grounded first (another side project). I'm
thus expecting that it will take until end 2018.

I you're interested, the in-development version on
https://github.com/anstoc/EcoImpactMapper_Dev has a class called
'RAccess' with a few functions that can be called e.g. with rJava.

Take care,
A.

**Comment by tyegagne** [comment]
Great thank you,


I hope your defense went well (I saw your practice at Hopkins), are you still around Hopkins at all? If you had 15-20 mins sometime it would be nice to get your perspective on the implementation of your software that we're attempting.


I could provide more details via email if you won't be around any time soon.


Thank you,

Tyler



Tyler Gagne
Assistant Research Scientist
P 831-648-4967


[http://www.montereybayaquarium.org/storage/email/logo_signature.gif]   Monterey Bay Aquarium
886 Cannery Row, Monterey, CA 93940
www.montereybayaquarium.org<http://www.montereybayaquarium.org>
Our mission is to inspire conservation of the ocean.



________________________________

**Comment by anstoc** [comment]
Hi Tyler,

thanks, yes, it went well. I'm not planning to come to Monterey again 
anytime soon and I'm traveling on and off. But we could skype or phone 
after August 23rd or I'm happy to answer any questions by e-mail before 
then.

All the best,
Andy
